server.port=8082

spring.application.name=mydata-api

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.profiles.active=local

bnkcard.api.base-url=http://192.168.0.130:8088

ci.salt=

bnk.server.url=http://bnk-server-url
# BNK 콜백 인증 시크릿 (BNKcard와 동일한 값으로 설정)
internal.callback.secret=
