server.port=8080

spring.application.name=mydata-api

ci.salt=${CI_SALT}

spring.datasource.url=jdbc:oracle:thin:@mydatamock_medium?TNS_ADMIN=/app/wallet/Wallet_MYDATAMOCK
spring.datasource.username=ADMIN
spring.datasource.password=${ORACLE_DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true