spring.datasource.url=jdbc:oracle:thin:@mydatamock_medium?TNS_ADMIN=C:/dev/Wallet_MYDATAMOCK
spring.datasource.username=ADMIN
spring.datasource.password=MYDATAmock1234!
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

ci.salt=local-mydata-ci-salt