server.port=8081

spring.application.name=mydata-api

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.profiles.active=local


# 로컬에 각자 bnkcard.api.base-url=http://자기 PC IP:8088
bnkcard.api.base-url=

ci.salt=

bnk.server.url=http://bnk-server-url
# BNK 콜백 인증 시크릿 (BNKcard와 동일한 값으로 설정)
internal.callback.secret=

migration.ci.enabled=false
