CREATE TABLE MYDATA_ADDITIONAL_REVIEW (
    ADDITIONAL_REVIEW_ID  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CREDIT_APP_ID         NUMBER(19)     NOT NULL,
    CI_VALUE              VARCHAR2(200)  NOT NULL,
    INCOME_DOC_KEY        VARCHAR2(500),
    ASSET_DOC_KEY         VARCHAR2(500),
    JOB_DOC_KEY           VARCHAR2(500),
    STATUS                VARCHAR2(20)   DEFAULT 'PENDING' NOT NULL,
    CREATED_AT            TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    COMPLETED_AT          TIMESTAMP
);
